-- 1. Total number of orders
-- Shows how many orders exist in the system
SELECT 
    COUNT(order_id) AS total_orders
FROM public.fct_orders;



-- 2. Total revenue
-- Shows total money generated from all orders
SELECT 
    SUM(total_amount) AS total_revenue
FROM public.fct_orders;



-- 3. Orders per customer
-- Shows how many orders each customer has placed
SELECT 
    customer_id,
    COUNT(order_id) AS total_orders
FROM public.fct_orders
GROUP BY customer_id;



-- 4. Revenue per product
-- Shows total revenue generated by each product
SELECT 
    product_id,
    SUM(total_amount) AS total_revenue
FROM public.fct_orders
GROUP BY product_id;

